config/routes.rb
TVTrackerPrototype::Application.routes.draw do

  root :to => 'pages#index'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  delete 'logout' => 'sessions#destroy', :as => 'logout'

  resources :sessions
  resources :users
  resources :shows, :only => [:index, :show, :create]
  get 'shows/:id/episodes' => 'episodes#list', :as => 'episodes'
  post 'shows/:id/sync' => 'shows#sync', :as => 'sync'
  post 'shows/:id/subscribe/:season/:episode' => 'subscriptions#subscribe', :as => 'subscribe'
  resources :subscriptions, :only => :destroy

  get '/subscriptions' => 'subscriptions#index', :as => 'subscriptions_admin'
  get 'users/:id/shows' => 'subscriptions#list', :as => 'subscriptions'
  get 'track' => 'subscriptions#list', :as => 'track'
  post 'subscriptions/:id/watch' => "subscriptions#watch", :as => 'watch'
  post 'subscriptions/:id/unwatch' => "subscriptions#unwatch", :as => 'unwatch'
end

app/models/show.rb
require 'api_helper'
require 'open-uri'

class Show < ActiveRecord::Base
  has_many :episodes, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

	validates :api_id, uniqueness: true
	validates :name, presence: true

	# add cached aliases for typos etc?
	attr_accessible :show_id, :api_id, :name, :ended, :airtime, :starring, :summary

	attr_accessible :poster
	has_attached_file :poster, :styles => { :medium => "300x390>", :thumb => "118x170>" }, :default_url => "300x390.gif"

	# putting this in a before_create rather than a before_validation skips validation. figure out how to avoid this.
	before_create do |show|
		show.fetch_and_load_data
		# manually validate and add typos to aliases
		false unless show.valid?	
	end

	# forces sort-descending on episodes
	alias_method :original_episodes, :episodes
	def episodes
		original_episodes.order("season_number asc, episode_number asc")
	end

	def last_episode
		episodes.last
	end

	def next_episode(episode)
		if episode.nil?
			next_episode = episodes.first
		else
			next_episode = episodes.where(season_number: episode.season_number, episode_number: episode.episode_number + 1).first
			next_episode = episodes.where(season_number: episode.season_number + 1, episode_number: 1).first if next_episode.nil?
		end
		next_episode
	end

	def prev_episode(episode)
		if(episode.nil?)
			nil
		elsif episode.episode_number > 1
			episodes.where(season_number: episode.season_number, episode_number: episode.episode_number - 1).first
		elsif episode.season_number > 1
			episodes.find_all_by_season_number(episode.season_number - 1).last
		else
			nil
		end
	end


	def self.query(name)
		show = self.where(:name => name).first_or_create
	end

	def fetch_and_load_data
		if name.blank?
			self.errors.add(:name, "Name is blank")
			raise ActiveRecord::Rollback
		end
		params = { show: name }.to_param
		data = ApiHelper.fetch(params)
		self.api_id = data[ApiHelper::API_DATA_KEYS[:api_id]].to_i
		self.name = data[ApiHelper::API_DATA_KEYS[:name]]
		self.ended = data[ApiHelper::API_DATA_KEYS[:ended]].present?
		self.airtime = data[ApiHelper::API_DATA_KEYS[:airtime]]
		begin
			self.poster = open(data[ApiHelper::API_DATA_KEYS[:thumbnail]])
		rescue Exception => e
			# Poster does not exist: leave nil
		end
		self.starring = data[ApiHelper::API_DATA_KEYS[:starring]]
		self.summary = data[ApiHelper::API_DATA_KEYS[:summary]]
	end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.order("name asc").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shows }
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = Show.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/new
  # GET /shows/new.json
  def new
    @show = Show.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(params[:show])

    respond_to do |format|
      begin
        if @show.save
          format.html { redirect_to shows_path(:anchor => @show.id), :flash => { notice: "<strong>Success: </strong> created #{@show.name}.", inline: true } }
          format.json { render json: @show, status: :created, location: @show }
        else
          format.html { redirect_to shows_path, alert: "<strong>Error: </strong> couldn't load new show \"#{@show.name}\"." }
          format.json { render json: @show.errors, status: :unprocessable_entity }
        end
      rescue
        # Surpress all errors
        format.html { redirect_to shows_path, alert: "<strong>Error: </strong> couldn't load new show \"#{@show.name}\"." }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shows/1
  # PUT /shows/1.json
  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update_attributes(params[:show])
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url }
      format.json { head :no_content }
    end
  end

  def sync
    @show = Show.find(params[:id])
    pre = @show.episodes.count
    begin
      Episode.pull_episodes(@show)
    rescue
      # Suppress all errors
    ensure
      if pre != @show.episodes.count 
        flash[:notice] = "<strong>Success: </strong> \"#{@show.name}\" updated!"
      else
        flash[:info] = "\"#{@show.name}\" is up to date."
      end
      flash[:inline] = true
      redirect_to shows_path(:anchor => @show.id)
    end
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_create_form.html.erb
<%= form_for @show, :html => { :class => 'form-inline' + (klass ? ' ' + klass : '') } do |f| %>
  <div class="control-group">
    <%= f.text_field :name, { :class => 'text_field', :placeholder => placeholder } %>
    <%= f.submit "Add Show", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/shows/_flash_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success shows-alert">
      <a class="close">×</a>
      <%= flash[:notice].html_safe %>
  </div>
<% end %>
<% if flash[:info] %>
  <div class="alert alert-info shows-alert">
      <a class="close">×</a>
      <%= flash[:info].html_safe %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-error shows-alert">
      <a class="close">×</a>
      <%= flash[:alert].html_safe %>
  </div>
<% end %>
<% if flash[:track] %>
  <div class="alert shows-alert">
      <a class="close">×</a>
      <%= flash[:track].html_safe %>
  </div>
<% end %>

app/views/shows/_form.html.erb
<%= form_for @show, :html => { :class => 'form-inline' } do |f| %>
  <div class="control-group">
    <%= f.text_field :name, { :class => 'text_field', :placeholder => placeholder } %>
    <%= f.submit "Add Show", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/shows/_search_form.html.erb
<form class="form-inline search-form control-group">
  <input type="text" class="search-box" placeholder="Search by name -- Press enter" />
  <button class="btn btn-success search-button">Search</button>
</form>

app/views/shows/edit.html.erb
<%- model_class = Show -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shows/index.html.erb
<%- model_class = Show -%>
<% @show = Show.new %>

<% if !flash[:inline] %>
  <div class="shows-top-alerts">
    <%= render :partial => 'flash_alert', :locals => {:flash => flash } %>
  </div>
<% else %>
  <div class="shows-inline-alerts">
    <%= render :partial => 'flash_alert', :locals => {:flash => flash } %>
  </div>
<% end %>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %>
    <span class="shows-top-form">
      <%= render :partial => 'search_form' %>
      <%= render :partial => 'create_form', :locals => {:placeholder => "Can't find what you're looking for?", :klass => "search-failed" } %>
    </span>
  </h1>
</div>

<table class="table table-striped" id="shows-table">
  <thead>
    <tr>
      <th class="table-name-column"><%= model_class.human_attribute_name(:name) %></th>
      <th class="table-airtime-column"><%= model_class.human_attribute_name(:airtime) %></th>
      <th class="table-next-episode-column">Next Episode (try <span class="label label-inverse shows-demo-button"><i class="icon-download-alt icon-white"></i> Update</span> for more)</th>
      <th class="table-actions-column"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shows.each do |show| %>
      <tr id="<%= show.id %>">
        <td class="table-name-column-entry"><%= link_to show.name, show_path(show), :class => 'btn'%>
          <br><%= link_to "Episode List", episodes_path(show), :class => 'episode-list-link' %></td>
        <td><%= if show.ended? then "No longer airing" else show.airtime || "Not available" end %></td>
        <td>
          <% ep = show.last_episode %>
          <% if ep %>
            <strong><%= ep.numbers_and_name %></strong>
            <br><em><%= ep.readable_airdate_with_verb %></em>
          <% else %>
            Not available (try pressing "update")
          <% end %>
        </td>
        <td>
          <% subscribed = current_user && current_user.subscribed?(show) %>
          <span class="shows-table-action">
            <% if subscribed %>
              <%= html_button_to '<i class="icon-remove-sign icon-white"></i> Untrack'.html_safe, subscription_path(id: current_user.get_subscription(show).id), :class => "btn btn-danger unsubscribe", :method => :delete %>
            <% else %>
              <%= html_button_to '&nbsp;&nbsp;<i class="icon-truck icon-white"></i> Track!&nbsp;&nbsp;'.html_safe, login_path, :class => "btn btn-warning subscribe", :method => :get %>
            <% end %>
          </span>
          <span class="shows-table-action">
            <%= html_button_to '<i class="icon-download-alt icon-white"></i> Update'.html_safe, sync_path(id: show.id), :class => "btn btn-inverse update" %>
          </span>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>
<div class="shows-bottom-form">Can't find what you're looking for? <%= render :partial => 'create_form', :locals => {:placeholder => "Name", :klass => nil} %></div>

<div id="dialog-form" title="#" style="display:none;" data-target="<%= subscribe_path(:sid, :season, :episode) %>">
  <p class="validateTips">Which episode are you on?</p>
  <form method="post">
  <fieldset>
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
    <label for="season">Season #</label>
    <input type="number" name="season" id="season" value="1" class="text ui-widget-content ui-corner-all" />
    <label for="episode">Episode #</label>
    <input type="number" name="episode" id="episode" value="1" class="text ui-widget-content ui-corner-all" />
  </fieldset>
  </form>
</div>
<%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.js" %>

<script type="text/javascript">
$(document).ready(function(){
  bindShowHandlers(<%= current_user ? true : false %>);
  bindHashHandlers(<%= flash[:inline] ? true : false %>);
});
</script>

app/views/shows/new.html.erb
<%- model_class = Show -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shows/show.html.erb
<%- model_class = Show -%>
<div class="span12 show-info-page">
  <div class="content-background"></div>
  <div class="page-header">
    <h1><%=t '.title', :default => @show.name %></h1>
  </div>

  <%= image_tag @show.poster.url(:medium), :class => "show-poster" %>

  <div style="float:left;">
    <dl class="dl-horizontal show-info">
      <dt><strong><%= model_class.human_attribute_name(:airtime) %></strong></dt>
      <dd><%= @show.airtime ? @show.airtime : "Unknown" %></dd>
      <br>
      <dt><strong>Ended?</strong></dt>
      <dd><%= @show.ended ? "Yes" : "Still airing" %></dd>
      <br>
      <dt><strong>Starring</strong></dt>
      <dd><%= @show.starring %></dd>
      <br>
      <dt><strong>Plot</strong></dt>
      <dd><%= @show.summary %></dd>
      <br>
      <dt><strong>Episodes</strong><dt>
      <dd><%= link_to "Episode List", episodes_path(@show), :class => 'btn btn-info'%></dd>
      <dd>
        <div class="form-actions back-button">
          <%= link_to "Back to list", shows_path, :class => 'btn'  %>
        </div>
      </dd>
    </dl>
  </div>
</div>