config/routes.rb
TVTrackerPrototype::Application.routes.draw do

  root :to => 'pages#index'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  delete 'logout' => 'sessions#destroy', :as => 'logout'

  resources :sessions
  resources :users
  resources :shows, :only => [:index, :show, :create]
  get 'shows/:id/episodes' => 'episodes#list', :as => 'episodes'
  post 'shows/:id/sync' => 'shows#sync', :as => 'sync'
  post 'shows/:id/subscribe/:season/:episode' => 'subscriptions#subscribe', :as => 'subscribe'
  resources :subscriptions, :only => :destroy

  get '/subscriptions' => 'subscriptions#index', :as => 'subscriptions_admin'
  get 'users/:id/shows' => 'subscriptions#list', :as => 'subscriptions'
  get 'track' => 'subscriptions#list', :as => 'track'
  post 'subscriptions/:id/watch' => "subscriptions#watch", :as => 'watch'
  post 'subscriptions/:id/unwatch' => "subscriptions#unwatch", :as => 'unwatch'
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="navbar-fixed-bottom">
    Made by <%= link_to "Leo Martel", "http://www.lpm.io" %>
    | <%= link_to "Feedback", "mailto:leo@lpm.io" %>
    <% if ENV['OSS'] %>
    | <%= link_to "Github", "http://www.github.com/lmartel/TVTracker" %>
    <% end %>
    | <a href="#" onclick="$("body").scrollTop(0);">Top</a>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "TV Tracker", root_path, :class => "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <% if current_user %>
            <%= smart_navbar_item "Track Episodes", track_path %>
          <% end %>
          <%= smart_navbar_item "Browse Shows", shows_path %>
          <% if current_user %>
            <li><%= link_to "Logout of <em>".html_safe + current_user.email + "</em>".html_safe, logout_path, :method => :delete %></li>
          <% else %>
            <%= smart_navbar_item "Login", login_path %>
            <%= smart_navbar_item "Signup", signup_path %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TVTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.min.css" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <% if Rails.env.production? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-42769593-1', 'lpm.io');
      ga('send', 'pageview');

    </script>
  <% end %>
</head>
<body onload="scrollIfHash()">
<div class="artsy-wrapper">
    <div class="artsy"></div>
</div>
<%= render :partial => "layouts/navbar" %>
<div class="container">
  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>
<%= render :partial => "layouts/footer" %>
<% if ENV['OSS'] %>
  <a href="https://github.com/lmartel/TVTracker"><img style="position: fixed; top: 0; right: 0; border: 0; z-index: 10001;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" alt="Fork me on GitHub"></a>
<% end %>
</body>
</html>